# Generated by Django 4.2.2 on 2023-07-04 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Category', '0003_alter_newsubcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('translit_name', models.CharField(unique=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='ProcessedProduct/')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('composition', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.newsubcategory')),
            ],
            options={
                'db_table': 'processed_product',
            },
        ),
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_category', models.CharField(blank=True, null=True)),
                ('raw_subcategory', models.CharField(blank=True, null=True)),
                ('raw_name', models.CharField()),
                ('url', models.URLField(unique=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='RawProduct/')),
                ('raw_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('raw_description', models.TextField(blank=True, null=True)),
                ('raw_composition', models.TextField(blank=True, null=True)),
                ('raw_country', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_fats', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('processed_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.processedproduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.shop')),
            ],
            options={
                'db_table': 'raw_product',
            },
        ),
        migrations.CreateModel(
            name='ProductHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.rawproduct')),
            ],
            options={
                'db_table': 'product_history-record',
            },
        ),
    ]
