# Generated by Django 4.2.2 on 2023-07-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_newsubcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsubcategory',
            table='NewSubcategory',
        ),
    ]
